Update valgrind-test.yml

diff --git a/.github/workflows/valgrind-test.yml b/.github/workflows/valgrind-test.yml
--- a/.github/workflows/valgrind-test.yml
+++ b/.github/workflows/valgrind-test.yml
@@ -2,9 +2,9 @@
 name: unit_tests_valgrind
 on:
   push:
-     branches: [ main, 'rbus-**' ]
+     branches: [ main, 'rbus-**' ,rbus-codecoverage ]
   pull_request:
-     branches: [ main, 'rbus-**' ]
+     branches: [ main, 'rbus-**', rbus-codecoverage ]
      types: [opened,synchronize]
   #workflow_run:
    #workflows: ["unit_test"]
@@ -61,7 +61,51 @@ jobs:
             mkdir -p /tmp/valgrind
       - name: Setup script
         run: |
-            cd ${{github.workspace}}/rbus
+           
+            cat << 'EOF' >memoryleak.sh
+            #!/bin/sh
+            
+            LOG_FOLDER="/tmp/valgrind"
+            ls -lt
+            SUMMARY_FILE=$GITHUB_STEP_SUMMARY  
+            LEAKS_FOUND=false
+            for LOG_FILE in $LOG_FOLDER/*.log; do
+             #cat $LOG_FILE 
+             if ( grep -q "ERROR SUMMARY" $LOG_FILE  && ! grep -q "ERROR SUMMARY: 0 errors" $LOG_FILE ); then
+             LEAKS_FOUND=true
+             echo "leak found set to  $LEAK_FOUND"
+             echo "Running logfile : $LOG_FILE" >>$SUMMARY_FILE
+             BINARY_PATH=$(basename $LOG_FILE .log)
+             echo "Running bin : $BINARY_PATH" >>$SUMMARY_FILE
+             #EXTRACT THE RELEVANT INFO
+             LEAK_SUMMARY=$(grep -A 5 "LEAK SUMMARY:" $LOG_FILE)
+             ERROR_SUMMARY=$(grep -A 1 "ERROR SUMMARY:" $LOG_FILE)
+             HEAP_SUMMARY=$(grep -A 5 "HEAP SUMMARY:" $LOG_FILE)
+              if [ -n "$LEAK_SUMMARY" ];then
+              echo " LEAK Summary" >>$SUMMARY_FILE
+              echo "$LEAK_SUMMARY"  >>$SUMMARY_FILE
+              fi
+              if [ -n "$ERROR_SUMMARY" ];then
+              echo "ERROR Summary" >>$SUMMARY_FILE
+              echo "$ERROR_SUMMARY"  >>$SUMMARY_FILE
+              fi
+              if [ -n "$HEAP_SUMMARY" ]; then
+              echo "HEAP SUMMARY" >>$SUMMARY_FILE
+              echo "$HEAP_SUMMARY" >>$SUMMARY_FILE
+              fi
+              #cat $LOG_FILE >>$SUMMARY_FILE
+             echo "*************************" >>$SUMMARY_FILE
+            fi
+            done
+            echo "leak found set to  $LEAKS_FOUND outside for"
+            if [ "$LEAKS_FOUND" = true ]; then
+              echo "inside leak found"
+              cd /tmp/valgrind
+              rm rf *.log
+              exit 1
+            fi
+            EOF
+            cd ${{github.workspace}}
             chmod a+x memoryleak.sh
       - name: Start rtrouted
         run: |
@@ -70,22 +114,6 @@ jobs:
           export LD_LIBRARY_PATH=$PREFIX/lib
           valgrind --leak-check=full   ./bin/rtrouted -f -l DEBUG  &
           #cd ${{github.workspace}}/rbus && ./memoryleak.sh
-      - name: Run RbusTestTimeoutValues Unit test with valgrind
-        run: |
-          cd install/usr
-          export PREFIX=$PWD
-          export LD_LIBRARY_PATH=$PREFIX/lib
-          valgrind --leak-check=full --log-file=/tmp/valgrind/rbusTestTimeoutValuesProvider.log ./bin/rbusTestTimeoutValuesProvider & 
-          valgrind --leak-check=full  --log-file=/tmp/valgrind/rbusTestTimeoutValuesConsumer.log ./bin/rbusTestTimeoutValuesConsumer & 
-          cd ${{github.workspace}}/rbus && ./memoryleak.sh 
-      - name: Run rbusTest Unit test with valgrind
-        run: |
-          cd install/usr
-          export PREFIX=$PWD
-          export LD_LIBRARY_PATH=$PREFIX/lib
-          valgrind --leak-check=full --log-file=/tmp/valgrind/rbusTestProvider.log ./bin/rbusTestProvider & 
-          valgrind --leak-check=full  --log-file=/tmp/valgrind/rbusTestConsumer.log ./bin/rbusTestConsumer -a  
-          cd ${{github.workspace}}/rbus && ./memoryleak.sh 
      
       - name: Run test with rbusmethod provider
         run: |
@@ -94,7 +122,7 @@ jobs:
           export LD_LIBRARY_PATH=$PREFIX/lib
           valgrind --leak-check=full --log-file=/tmp/valgrind/rbusMethodProvider.log ./bin/rbusMethodProvider & 
           valgrind --leak-check=full  --log-file=/tmp/valgrind/rbusMethodConsumer.log ./bin/rbusMethodConsumer -a 
-          cd ${{github.workspace}}/rbus && ./memoryleak.sh   
+          cd ${{github.workspace}} && ./memoryleak.sh  
       - name: Run multiRbusOpenGet Unit test with Valgrind
         run: |
           cd install/usr
@@ -102,7 +130,7 @@ jobs:
           export LD_LIBRARY_PATH=$PREFIX/lib
           valgrind --leak-check=full --log-file=/tmp/valgrind/multiRbusGetProvider.log ./bin/multiRbusOpenRbusGetProvider  & 
           valgrind --leak-check=full --log-file=/tmp/valgrind/multiRbusGetConsumer.log ./bin/multiRbusOpenRbusGetConsumer &
-          cd ${{github.workspace}}/rbus && ./memoryleak.sh 
+          cd ${{github.workspace}} && ./memoryleak.sh
       - name: Run multiRbusOpenSet Unit test with Valgrind
         run: |
           cd install/usr
@@ -110,7 +138,7 @@ jobs:
           export LD_LIBRARY_PATH=$PREFIX/lib
           valgrind --leak-check=full --log-file=/tmp/valgrind/multiRbusOpenRbusGetProvider.log ./bin/multiRbusOpenRbusGetProvider  &
           valgrind --leak-check=full --log-file=/tmp/valgrind/multiRbusOpenRbusSetConsumer.log ./bin/multiRbusOpenRbusSetConsumer &
-          cd ${{github.workspace}}/rbus && ./memoryleak.sh 
+          cd ${{github.workspace}} && ./memoryleak.sh
       #- name: Run Gtest Cases with Valgrind
         #run: |
           #cd install/usr
@@ -118,10 +146,10 @@ jobs:
           #export LD_LIBRARY_PATH=$PREFIX/lib
           #valgrind --leak-check=full --log-file=/tmp/valgrind/rbus_session_manager.log ./bin/rbus_session_manager &
           #valgrind --leak-check=full --log-file=/tmp/valgrind/rbus_gtest.log --track-origins=yes --verbose ./bin/rbus_gtest.bin  
-      - name: Stop rtrouted
-        run: |
-          cd install/usr
-          export PREFIX=$PWD
-          export LD_LIBRARY_PATH=$PREFIX/lib
-          killall -9 rtrouted
+     # - name: Stop rtrouted
+        #run: |
+          #cd install/usr
+          #export PREFIX=$PWD
+          #export LD_LIBRARY_PATH=$PREFIX/lib
+          #killall -9 rtrouted
           
