Update valgrind-test.yml

diff --git a/.github/workflows/valgrind-test.yml b/.github/workflows/valgrind-test.yml
--- a/.github/workflows/valgrind-test.yml
+++ b/.github/workflows/valgrind-test.yml
@@ -59,7 +59,48 @@ jobs:
       - name: Setup script
         run: |
             mkdir -p /tmp/valgrind
-            cd ${{github.workspace}}/rbus
+            cat << 'EOF' >memoryleak.sh
+            #!/bin/sh
+            
+            LOG_FOLDER="/tmp/valgrind"
+            SUMMARY_FILE=$GITHUB_STEP_SUMMARY  
+            LEAKS_FOUND=false
+            for LOG_FILE in $LOG_FOLDER/*.log; do
+             #cat $LOG_FILE 
+             if ( grep -q "ERROR SUMMARY" $LOG_FILE  && ! grep -q "ERROR SUMMARY: 0 errors" $LOG_FILE ); then
+             LEAKS_FOUND=true
+             echo "leak found set to  $LEAK_FOUND"
+             echo "Running logfile : $LOG_FILE" >>$SUMMARY_FILE
+             BINARY_PATH=$(basename $LOG_FILE .log)
+             echo "Running bin : $BINARY_PATH" >>$SUMMARY_FILE
+             #EXTRACT THE RELEVANT INFO
+             LEAK_SUMMARY=$(grep -A 5 "LEAK SUMMARY:" $LOG_FILE)
+             ERROR_SUMMARY=$(grep -A 1 "ERROR SUMMARY:" $LOG_FILE)
+             HEAP_SUMMARY=$(grep -A 5 "HEAP SUMMARY:" $LOG_FILE)
+              if [ -n "$LEAK_SUMMARY" ];then
+              echo " LEAK Summary" >>$SUMMARY_FILE
+              echo "$LEAK_SUMMARY"  >>$SUMMARY_FILE
+              fi
+              if [ -n "$ERROR_SUMMARY" ];then
+              echo "ERROR Summary" >>$SUMMARY_FILE
+              echo "$ERROR_SUMMARY"  >>$SUMMARY_FILE
+              fi
+              if [ -n "$HEAP_SUMMARY" ]; then
+              echo "HEAP SUMMARY" >>$SUMMARY_FILE
+              echo "$HEAP_SUMMARY" >>$SUMMARY_FILE
+              fi
+              #cat $LOG_FILE >>$SUMMARY_FILE
+             echo "*************************" >>$SUMMARY_FILE
+            fi
+            done
+            echo "leak found set to  $LEAKS_FOUND outside for"
+            if [ "$LEAKS_FOUND" = true ]; then
+              echo "inside leak found"
+              rm -rf /tmp/valgrind/*
+              exit 1
+            fi
+            EOF
+            cd ${{github.workspace}}
             chmod a+x memoryleak.sh
       - name: Start rtrouted
         run: |
@@ -76,7 +117,7 @@ jobs:
           export LD_LIBRARY_PATH=$PREFIX/lib
           valgrind --leak-check=full --log-file=/tmp/rbusMethodProvider.log ./bin/rbusMethodProvider & 
           valgrind --leak-check=full  --log-file=/tmp/rbusMethodConsumer.log ./bin/rbusMethodConsumer -a 
-          cd ${{github.workspace}}/rbus && ./memoryleak.sh  
+          cd ${{github.workspace}} && ./memoryleak.sh  
       - name: Run multiRbusOpenGet Unit test with Valgrind
         run: |
           cd install/usr
@@ -84,7 +125,7 @@ jobs:
           export LD_LIBRARY_PATH=$PREFIX/lib
           valgrind --leak-check=full --log-file=/tmp/multiRbusGetProvider.log ./bin/multiRbusOpenRbusGetProvider  & 
           valgrind --leak-check=full --log-file=/tmp/multiRbusGetConsumer.log ./bin/multiRbusOpenRbusGetConsumer &
-          cd ${{github.workspace}}/rbus && ./memoryleak.sh
+          cd ${{github.workspace}} && ./memoryleak.sh
       - name: Run multiRbusOpenSet Unit test with Valgrind
         run: |
           cd install/usr
@@ -92,7 +133,7 @@ jobs:
           export LD_LIBRARY_PATH=$PREFIX/lib
           valgrind --leak-check=full --log-file=/tmp/multiRbusOpenRbusGetProvider.log ./bin/multiRbusOpenRbusGetProvider  &
           valgrind --leak-check=full --log-file=/tmp/multiRbusOpenRbusSetConsumer.log ./bin/multiRbusOpenRbusSetConsumer &
-          cd ${{github.workspace}}/rbus && ./memoryleak.sh
+          cd ${{github.workspace}} && ./memoryleak.sh
       #- name: Run Gtest Cases with Valgrind
         #run: |
           #cd install/usr
